apiVersion: apps/v1
kind: Deployment
metadata:
 name: portfolio
 namespace: proyectoportfolio
spec:
 replicas: 1
 selector:
   matchLabels:
     app: portfolio
 template:
   metadata:
     labels:
       app: jose-portfolio
   spec:
     containers:
       - name: portfolio
         image: jose196/portfolio-jose:latest
         # imagePullPolicy: Never
         ports:
           - containerPort: 80
